
spring:
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/nwork?serverTimezone=UTC
    username: root
    password: 5641
    dbcp2:
      max-idle: 10    
      min-idle: 5
      initial-size: 5
      max-wait-millis: 1000
 