#冒号后面一定加空格
server:
  port: 8081
  servlet:
    context-path: /testyml

#日志
logging:
  config: logback-spring.xml
  level:
    com.example.log: trace

       

spring:
  #yml文件名一定要以“application-”开头 
  profiles:
    active: prod
  #aop  
  aop:
    proxy-target-class: true
  #热部署
  thymeleaf:        
    cache: true  #启动缓存
  devtools:
    restart:
      enabled: true    #部署生效
      additional-paths:   #重启目录
      - src/main/java
      exclude: WEB-INF/**  #不重启的目录
  #用的是spring-boot-starter-quartz 持久化,  springboot自带的, 下面设置和properties表一样
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    initialize-schema: embedded
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true