#冒号后面一定加空格
server:
  port: 8081
  servlet:
    context-path: /testyml
  tomcat:
    max-http-form-post-size: 102400

#日志
logging:
  config: logback-spring.xml
  level:
    com.example.log: trace
#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
     


spring:
  #yml文件名一定要以“application-”开头 
  profiles:
    active: dev
  #aop  
  aop:
    proxy-target-class: true
  #热部署
  thymeleaf:        
    cache: true  #启动缓存
  devtools:
    restart:
      enabled: true    #部署生效
      additional-paths:   #重启目录
      - src/main/java
      exclude: WEB-INF/**  #不重启的目录
  #用的是spring-boot-starter-quartz 持久化,  springboot自带的, 下面设置和properties表一样
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    initialize-schema: embedded
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  #redis 配置          
  redis:
    host: 127.0.0.1        #Redis服务器地址
    port: 6379             #Redis服务器连接端口
    database: 0            #Redis数据库索引（默认为0）
    jedis:
      pool:
        max-active: 50     #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000     #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20       #连接池中的最大空闲连接
        min-idle: 2        #连接池中的最小空闲连接
    timeout:   5000        #连接超时时间（毫秒）
       
  #MQ     
  rabbitmq:
    host: 127.0.0.1    
         
