spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #?serverTimezone=UTC解决时区的报错
      url:  jdbc:mysql://localhost:3306/nwork?serverTimezone=UTC
      username: root
      password: 5641
      initial-size: 3
      max-active: 10
      min-idle: 2
      max-wait: 5
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query:  select 'x'
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      #如果过滤filters: log4j ,记得加依赖
      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      filters: stat
      filter:
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 5000 
          