#冒号后面一定加空格
server:
  port: 8080

logging:
  config: logback-spring.xml
  level:
    com.example.log: trace
       
#yml文件名一定要以“application-”开头 
spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/nwork
    username: root
    password: 5641
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

